name: "Update component database"
on:
  push:
    branches: deploy-fixes
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  build_and_update:
    name: "Update component database and frontend"
    runs-on: ubuntu-22.04
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            nodejs npm fuse-zip
      - name: Build frontend
        run: |
          cd web
          export BASEURL=https://dougy83.github.io/jlcparts
          npm install --silent
          NODE_ENV=production PUBLIC_URL=${BASEURL} npm run build
          touch .nojekyll
      - name: Update database
        run: |
          set -x
          mkdir -p web/build/data/

          sudo pip3 install -e .

          wget -q https://yaqwsx.github.io/jlcparts/data/cache.zip https://yaqwsx.github.io/jlcparts/data/cache.z{01..30} || true

          # combine zip parts into single file
          cat cache.z* > cache-combined-bad.zip
          zip -FF cache-combined-bad.zip -O cache-combined.zip <<EOF
          z
          
          EOF

          mkdir /tmp/cachezip
          fuse-zip cache-combined.zip /tmp/cachezip
          jlcparts buildtables --jobs 0 \
                    --ignoreoldstock 120 \
                    /tmp/cachezip/cache.sqlite3 web/build/data
          fusermount -u /tmp/cachezip

          rm -f web/build/data/cache.z*

                    
      - name: Tar artifact # Artifact are case insensitive, this is workaround
        run: tar -czf web_build.tar.gz web/build/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: web_build
          path: web_build.tar.gz
          retention-days: 14
  deploy:
    name: "Deploy"
    runs-on: ubuntu-22.04
    needs: build_and_update
    if: github.ref == 'refs/heads/deploy-fixes'
    steps:
      - name: Checkout # Required for GH-pages deployment
        uses: actions/checkout@v3
      - name: "Download web"
        uses: actions/download-artifact@v3
        with:
          name: web_build
      - name: Untar artifact
        run: tar -xzf web_build.tar.gz
      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: doug-gh-pages
          folder: web/build
          single-commit: true
